regions = ["us-west-1"]
region = "us-west-1"
cidr_block = "10.0.0.0/16"
enable_dns_support = true
enable_dns_hostnames = true
tags = {
  Environment = "dev"
  Owner       = "dev-team"
}
subnets = ["subnet-xxxxxxxx"]
alb_name = "dev-backend-alb"
alb_internal = false
target_group_name = "dev-backend-tg"
target_group_port = 8080
health_check_path = "/"
cluster_name = "dev-backend-cluster"
task_family = "dev-backend-task"
execution_role_arn = "arn:aws:iam::123456789012:role/ecsTaskExecutionRole"
task_role_arn = "arn:aws:iam::123456789012:role/ecsTaskRole"
image = "123456789012.dkr.ecr.us-west-1.amazonaws.com/dev-backend:latest"
environment = [
  { name = "NODE_ENV", value = "development" }
]
service_name = "dev-backend-service"
desired_count = 1
assign_public_ip = true
db_identifier = "dev-postgres"
engine_version = "15.3"
instance_class = "db.t3.micro"
allocated_storage = 20
db_username = "devuser"
db_password = "devpassword"
db_name = "devdb"
db_subnet_group_name = "dev-subnet-group"
multi_az = false
lambda_cidr_block = "10.0.0.0/16"
s3_buckets = ["dev-app-data", "dev-logs"]
replication_role_arn = "arn:aws:iam::123456789012:role/s3-replication-role"
replication_destination_bucket_arn = "arn:aws:s3:::dev-app-data-replica"
waf_name = "dev-backend-waf"
waf_description = "WAF for Dev Fargate Backend"
waf_scope = "REGIONAL"
cf_comment = "CloudFront for Dev Backend"
cf_default_root_object = "index.html"
rds_host = "<your-dev-rds-endpoint>"
rds_user = "<your-dev-rds-username>"
rds_password = "<your-dev-rds-password>"
rds_db = "<your-dev-rds-db-name>"
rds_port = 5432
